/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_DragonGameBackendJNI */

#ifndef _Included_src_DragonGameBackendJNI
#define _Included_src_DragonGameBackendJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_DragonGameBackendJNI
 * Method:    createDragon
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_src_DragonGameBackendJNI_createDragon
  (JNIEnv *, jobject);

/*
 * Class:     src_DragonGameBackendJNI
 * Method:    getDragonHealth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_src_DragonGameBackendJNI_getDragonHealth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_DragonGameBackendJNI
 * Method:    attackDragon
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_src_DragonGameBackendJNI_attackDragon
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     src_DragonGameBackendJNI
 * Method:    dragonAttack
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_src_DragonGameBackendJNI_dragonAttack
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     src_DragonGameBackendJNI
 * Method:    allStructuresDestroyed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_src_DragonGameBackendJNI_allStructuresDestroyed
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_DragonGameBackendJNI
 * Method:    getPlayerFailures
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_src_DragonGameBackendJNI_getPlayerFailures
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_DragonGameBackendJNI
 * Method:    destroyDragon
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_src_DragonGameBackendJNI_destroyDragon
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_DragonGameBackendJNI
 * Method:    resetGame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_src_DragonGameBackendJNI_resetGame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_DragonGameBackendJNI
 * Method:    getStructureStatus
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_DragonGameBackendJNI_getStructureStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_DragonGameBackendJNI
 * Method:    getAvailableStructures
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_DragonGameBackendJNI_getAvailableStructures
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_DragonGameBackendJNI
 * Method:    reviveUnits
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_src_DragonGameBackendJNI_reviveUnits
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_DragonGameBackendJNI
 * Method:    attackDragonWithDamage
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_src_DragonGameBackendJNI_attackDragonWithDamage
  (JNIEnv *, jobject, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
