/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_BaseBackendJNI */

#ifndef _Included_src_BaseBackendJNI
#define _Included_src_BaseBackendJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_BaseBackendJNI
 * Method:    createBase
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_src_BaseBackendJNI_createBase
  (JNIEnv *, jobject);

/*
 * Class:     src_BaseBackendJNI
 * Method:    destroyBase
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_src_BaseBackendJNI_destroyBase
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_BaseBackendJNI
 * Method:    addGold
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_src_BaseBackendJNI_addGold
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     src_BaseBackendJNI
 * Method:    build
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_src_BaseBackendJNI_build
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     src_BaseBackendJNI
 * Method:    getGold
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_src_BaseBackendJNI_getGold
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_BaseBackendJNI
 * Method:    hasTownhall
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_src_BaseBackendJNI_hasTownhall
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_BaseBackendJNI
 * Method:    getTownhallLevel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_src_BaseBackendJNI_getTownhallLevel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_BaseBackendJNI
 * Method:    getStructureCount
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_src_BaseBackendJNI_getStructureCount
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     src_BaseBackendJNI
 * Method:    getStructureCost
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_src_BaseBackendJNI_getStructureCost
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     src_BaseBackendJNI
 * Method:    resetGame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_src_BaseBackendJNI_resetGame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_BaseBackendJNI
 * Method:    getMaxLimit
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_src_BaseBackendJNI_getMaxLimit
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
