/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_GridGameGUI */

#ifndef _Included_src_GridGameGUI
#define _Included_src_GridGameGUI
#ifdef __cplusplus
extern "C" {
#endif
#undef src_GridGameGUI_FOCUS_TRAVERSABLE_UNKNOWN
#define src_GridGameGUI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef src_GridGameGUI_FOCUS_TRAVERSABLE_DEFAULT
#define src_GridGameGUI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef src_GridGameGUI_FOCUS_TRAVERSABLE_SET
#define src_GridGameGUI_FOCUS_TRAVERSABLE_SET 2L
#undef src_GridGameGUI_TOP_ALIGNMENT
#define src_GridGameGUI_TOP_ALIGNMENT 0.0f
#undef src_GridGameGUI_CENTER_ALIGNMENT
#define src_GridGameGUI_CENTER_ALIGNMENT 0.5f
#undef src_GridGameGUI_BOTTOM_ALIGNMENT
#define src_GridGameGUI_BOTTOM_ALIGNMENT 1.0f
#undef src_GridGameGUI_LEFT_ALIGNMENT
#define src_GridGameGUI_LEFT_ALIGNMENT 0.0f
#undef src_GridGameGUI_RIGHT_ALIGNMENT
#define src_GridGameGUI_RIGHT_ALIGNMENT 1.0f
#undef src_GridGameGUI_serialVersionUID
#define src_GridGameGUI_serialVersionUID -7644114512714619750i64
#undef src_GridGameGUI_serialVersionUID
#define src_GridGameGUI_serialVersionUID 4613797578919906343i64
#undef src_GridGameGUI_INCLUDE_SELF
#define src_GridGameGUI_INCLUDE_SELF 1L
#undef src_GridGameGUI_SEARCH_HEAVYWEIGHTS
#define src_GridGameGUI_SEARCH_HEAVYWEIGHTS 1L
#undef src_GridGameGUI_OPENED
#define src_GridGameGUI_OPENED 1L
#undef src_GridGameGUI_serialVersionUID
#define src_GridGameGUI_serialVersionUID 4497834738069338734i64
#undef src_GridGameGUI_DEFAULT_CURSOR
#define src_GridGameGUI_DEFAULT_CURSOR 0L
#undef src_GridGameGUI_CROSSHAIR_CURSOR
#define src_GridGameGUI_CROSSHAIR_CURSOR 1L
#undef src_GridGameGUI_TEXT_CURSOR
#define src_GridGameGUI_TEXT_CURSOR 2L
#undef src_GridGameGUI_WAIT_CURSOR
#define src_GridGameGUI_WAIT_CURSOR 3L
#undef src_GridGameGUI_SW_RESIZE_CURSOR
#define src_GridGameGUI_SW_RESIZE_CURSOR 4L
#undef src_GridGameGUI_SE_RESIZE_CURSOR
#define src_GridGameGUI_SE_RESIZE_CURSOR 5L
#undef src_GridGameGUI_NW_RESIZE_CURSOR
#define src_GridGameGUI_NW_RESIZE_CURSOR 6L
#undef src_GridGameGUI_NE_RESIZE_CURSOR
#define src_GridGameGUI_NE_RESIZE_CURSOR 7L
#undef src_GridGameGUI_N_RESIZE_CURSOR
#define src_GridGameGUI_N_RESIZE_CURSOR 8L
#undef src_GridGameGUI_S_RESIZE_CURSOR
#define src_GridGameGUI_S_RESIZE_CURSOR 9L
#undef src_GridGameGUI_W_RESIZE_CURSOR
#define src_GridGameGUI_W_RESIZE_CURSOR 10L
#undef src_GridGameGUI_E_RESIZE_CURSOR
#define src_GridGameGUI_E_RESIZE_CURSOR 11L
#undef src_GridGameGUI_HAND_CURSOR
#define src_GridGameGUI_HAND_CURSOR 12L
#undef src_GridGameGUI_MOVE_CURSOR
#define src_GridGameGUI_MOVE_CURSOR 13L
#undef src_GridGameGUI_NORMAL
#define src_GridGameGUI_NORMAL 0L
#undef src_GridGameGUI_ICONIFIED
#define src_GridGameGUI_ICONIFIED 1L
#undef src_GridGameGUI_MAXIMIZED_HORIZ
#define src_GridGameGUI_MAXIMIZED_HORIZ 2L
#undef src_GridGameGUI_MAXIMIZED_VERT
#define src_GridGameGUI_MAXIMIZED_VERT 4L
#undef src_GridGameGUI_MAXIMIZED_BOTH
#define src_GridGameGUI_MAXIMIZED_BOTH 6L
#undef src_GridGameGUI_serialVersionUID
#define src_GridGameGUI_serialVersionUID 2673458971256075116i64
#undef src_GridGameGUI_GRID_SIZE
#define src_GridGameGUI_GRID_SIZE 10L
#undef src_GridGameGUI_EMPTY
#define src_GridGameGUI_EMPTY 46L
#undef src_GridGameGUI_PLAYER
#define src_GridGameGUI_PLAYER 80L
#undef src_GridGameGUI_ENEMY
#define src_GridGameGUI_ENEMY 69L
#undef src_GridGameGUI_WALL
#define src_GridGameGUI_WALL 120L
/*
 * Class:     src_GridGameGUI
 * Method:    calculateEnemyMove
 * Signature: ([[C[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_src_GridGameGUI_calculateEnemyMove
  (JNIEnv *, jobject, jobjectArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
