/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_GridGameBackendJNI */

#ifndef _Included_src_GridGameBackendJNI
#define _Included_src_GridGameBackendJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_GridGameBackendJNI
 * Method:    calculateEnemyMove
 * Signature: ([[C[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_src_GridGameBackendJNI_calculateEnemyMove
  (JNIEnv *, jobject, jobjectArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
